# Generated by Django 6.0.4 on 2026-04-16 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssetRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(blank=True, db_index=True, max_length=64, unique=True)),
                ('employee_name', models.CharField(max_length=150)),
                ('project', models.CharField(max_length=150)),
                ('job_title', models.CharField(max_length=150)),
                ('approved_by', models.CharField(blank=True, max_length=150)),
                ('approval_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AssetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(max_length=150)),
                ('date_issued', models.DateField()),
                ('issued_by', models.CharField(max_length=150)),
                ('employee_signature', models.CharField(blank=True, max_length=150)),
                ('asset_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='assets.assetrecord')),
            ],
        ),
    ]
