# Generated by Django 6.0.4 on 2026-04-16 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetitem',
            name='employee_signature',
            field=models.BooleanField(default=False),
        ),
    ]
