# Generated by Django 6.0.4 on 2026-04-29 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_alter_assetitem_employee_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetitem',
            name='asset_type',
            field=models.CharField(choices=[('laptop', 'Laptop'), ('desktop', 'Desktop Computer'), ('monitor', 'Monitor'), ('mobile_phone', 'Mobile Phone'), ('tablet', 'Tablet'), ('printer', 'Printer'), ('keyboard', 'Keyboard'), ('mouse', 'Mouse'), ('usb_drive', 'USB Drive'), ('external_hdd', 'External Hard Drive'), ('headset', 'Headset'), ('webcam', 'Webcam'), ('router', 'Router / Switch'), ('ups', 'UPS / Battery Backup'), ('other', 'Other')], max_length=150),
        ),
    ]
