# Generated by Django 6.0.4 on 2026-04-17 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssetFaultReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(blank=True, db_index=True, max_length=64, unique=True)),
                ('date', models.DateField(db_index=True)),
                ('employee_name', models.CharField(max_length=150)),
                ('job_title', models.CharField(max_length=150)),
                ('asset_type', models.CharField(max_length=150)),
                ('asset_serial_number', models.CharField(max_length=150)),
                ('fault_description', models.TextField()),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], db_index=True, default='low', max_length=10)),
                ('actions_taken', models.TextField(blank=True)),
                ('additional_comments', models.TextField(blank=True)),
                ('employee_signed', models.BooleanField(default=False)),
                ('employee_signed_date', models.DateField(blank=True, null=True)),
                ('assigned_to', models.CharField(blank=True, max_length=150)),
                ('it_signature', models.BooleanField(default=False)),
                ('date_received', models.DateField(blank=True, null=True)),
                ('resolution_date', models.DateField(blank=True, null=True)),
                ('approved_by', models.CharField(blank=True, max_length=150)),
                ('approved_signature', models.BooleanField(default=False)),
                ('approval_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
