# Generated by Django 6.0.4 on 2026-04-17 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset_faults', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetfaultreport',
            name='employee_signed',
        ),
        migrations.RemoveField(
            model_name='assetfaultreport',
            name='employee_signed_date',
        ),
    ]
