# Generated by Django 6.0.4 on 2026-04-17 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset_faults', '0002_remove_assetfaultreport_employee_signed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetfaultreport',
            name='approval_date',
        ),
        migrations.RemoveField(
            model_name='assetfaultreport',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='assetfaultreport',
            name='approved_signature',
        ),
    ]
