# Generated by Django 6.0.4 on 2026-04-17 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_faults', '0003_remove_assetfaultreport_approval_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetfaultreport',
            name='resolution_description',
            field=models.TextField(blank=True),
        ),
    ]
