# Generated by Django 6.0.4 on 2026-04-13 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FaultReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(db_index=True, max_length=64, unique=True)),
                ('report_date', models.DateField(db_index=True)),
                ('report_time', models.TimeField()),
                ('reporter_name', models.CharField(max_length=150)),
                ('role', models.CharField(max_length=100)),
                ('reporter_contact', models.CharField(max_length=150)),
                ('location', models.CharField(max_length=255)),
                ('complaint_summary', models.TextField()),
                ('investigation_findings', models.TextField(blank=True)),
                ('resolution', models.TextField(blank=True)),
                ('action_taken_by', models.CharField(blank=True, max_length=150)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], db_index=True, default='OPEN', max_length=20)),
                ('date_of_resolution', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-report_date', '-report_time', '-id'],
                'indexes': [models.Index(fields=['status', 'report_date'], name='fault_logs__status_d20b47_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('date_of_resolution__isnull', True), ('status__in', ['OPEN', 'IN_PROGRESS'])), models.Q(('date_of_resolution__isnull', False), ('status__in', ['RESOLVED', 'CLOSED'])), _connector='OR'), name='faultreport_resolution_date_consistency')],
            },
        ),
    ]
