# Generated by Django 6.0.4 on 2026-04-14 10:32

import django.core.validators
import django.db.models.deletion
import fault_logs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fault_logs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaultReportAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=fault_logs.models.fault_report_attachment_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpg', 'jpeg', 'gif', 'webp', 'bmp', 'txt', 'csv', 'doc', 'docx', 'xls', 'xlsx'])])),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('fault_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='fault_logs.faultreport')),
            ],
            options={
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['fault_report', '-uploaded_at'], name='fault_logs__fault_r_eb57e0_idx')],
            },
        ),
    ]
