# Generated by Django 6.0.4 on 2026-04-14 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fault_logs', '0002_faultreportattachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faultreport',
            name='reference_number',
            field=models.CharField(blank=True, db_index=True, max_length=64, unique=True),
        ),
    ]
