# Generated by Django 6.0.4 on 2026-04-14 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PPEIssueRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=150)),
                ('project', models.CharField(blank=True, max_length=150)),
                ('job_title', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PPEItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ppe_type', models.CharField(max_length=150)),
                ('date_issued', models.DateField()),
                ('employee_signature', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ppe_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ppe_records.ppeissuerecord')),
            ],
        ),
    ]
