# Generated by Django 6.0.4 on 2026-04-20 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckbookEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(blank=True, db_index=True, max_length=64, unique=True)),
                ('date', models.DateField()),
                ('ref_code', models.CharField(blank=True, max_length=50)),
                ('num', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField()),
                ('category', models.CharField(blank=True, max_length=150)),
                ('withdrawal_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('deposit_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
    ]
